### PR TITLE
revise make and addtogallery components

### PR DESCRIPTION
**Pull request by adam-adair**
Added "Create a New Pixtery" button to Daily Submission.
Make screen can either use the default flow or the direct-to-daily flow. D2D flow doesn't offer to share the link and instead navigates to the "confirm submission" screen.
D2D Pixteries are still added to your sent list. The Make screen is reset to default after navigating away.

### CODE REVIEW

**Comment by mavirex** [comment]
I walked through this process and found what I think might be an issue; does anyone else experience this?

1. Navigate to the Daily page, and click Submit a Daily Pixtery
image

2. Click Create a New Pixtery
image

3. Which takes you to the Make screen with the updated Submit Daily button
image

4. Make a Pixtery and click Submit Daily
image

5. Building a Pixtery loading screen
image

6. THE ISSUE: I'm taken back to my Sent list from Step 2 before the modal to confirm my Daily opens, and I stay on this list for a few seconds. The first time this happened, I thought that there might have been a glitch that prevented my pixtery from being submitted. During this period, I can't click on anything while I wait for the modal to open:
image

7. After a few seconds, the Submit Daily modal opens:
image

Does anyone else experience this delay between clicking the Submit Daily button and seeing the modal?

**Comment by adam-adair** [comment]
@mavirex I've made some changes that I hope solve the problem. They seem to work on my end. I removed the "display painful ads" part of the Make component, since we're not showing ads there anyway. I also slightly refactored the code there.

**Comment by fugoto** [comment]
Thanks for doing this! It worked great for me without the delay that you were talking about above - I created a daily and the modal opened up right away in front of the sent list. I did this twice and it worked well both times.

**Comment by garber34** [comment]
I don't get the delay. For me the modal pops up at the same time that the phone navigates to the send list and the modal is translucent until the navigation animation ends.

**Comment by adam-adair** [comment]
Having hard time picturing that. Does it look right or does it look weird?

**Pull request merged**
